baseURL  =  "https://lzsay.com"
languageCode = "zh-CN"
# DefaultContentLanguage = "zh-CN"
title  =  "神呆日志"
subtitle = "总有些美好值得为之奋斗！"


theme  =  "farallon"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 5
timeout = '10m'
ignoreErrors = ["error-remote-getjson","error-remote-getcsv"]

[permalinks]
  [permalinks.section]
    post = '/archive'
  [permalinks.page]
    post = '/story/:slugorfilename/'
    page = '/:slugorfilename/'  
  [permalinks.term]
    tags = '/tag/:slug/'
    categories = '/category/:slug/'
  [permalinks.taxonomy]
    tags = '/topics/'
    categories = '/cats/'

[menu]
  [[menu.main]]
  name="分类"
  url="/cats/"
  weight="1"
  [[menu.main]]
  name="书影音"
  url="/movies/"
  weight="1"
  [[menu.main]]
  name="归档"
  url="/archive/"
  weight="1"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="1"
   [[menu.main]]
  name="标签"
  url="/topics/"
  weight="1"
  
[taxonomies]
  category = 'categories'
  tag = 'tags'
[Author]
  name = "linexy"
  

  [markup.tableOfContents]
  endLevel = 5
  startLevel = 3
    
[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]

[related]
  includeNewer = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
