baseURL = "https://lzsay.com/"
languageCode = "zh-cn"
theme = "jingzhe_2"
themesDir = "themes"
title = "空白Koobai"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true
hasCJKLanguage = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[permalinks]
  posts = '/:slug/'

[params.artalk]
    server="https://memos.lzsay.com"
    site="Koobai 空白生活"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = "sport"
    name = "骑行"
    url = "https://sport.koobai.com/"
    weight = 3